CAREGIVERS_COL_ORDER = [
    "franchise",
    "franchise_name",
    "franchise_acro",
    "caregiver_profile_key",
    "caregiver_id",
    "caregiver_name",
    "location",
    "email",
    "date_of_birth",
    "gender",
    "city",
    "hire_date",
    "first_care_log_date",
    "last_care_log_date",
    "termination_date",
    "inactive",
    "hours_wanted_weekly",
    "role_type",
    "caregiver_tags",
]

# Clients (WellSky)
CLIENTS_COL_ORDER = [
    "franchise",
    "franchise_name",
    "franchise_acro",
    "client_id",
    "full_name",
    "city",
    "state",
    "postal_code",
    "address",
    "address_line_2",
    "start_date",
    "first_carelog_date",
    "last_carelog_date",
    "date_deactivated",
    "deactivated",
    "deactivation_reason",
    "client_referrer",
    "referral_source_type",
    "city_tax",
    "location",
    "tags",
]
